feat: simplified collect screen
drips-network/app pull request #691
Opened 2023-09-26 12:27 UTC by efstajas

Most users will only be collecting split income (from Drip Lists and Projects), so this aims to simplify their collect screen by hiding most streaming-related stuff.

- Hide "Income from concluded cycles" field if there's no receivable stream income.
- Rename "Splittable SYMBOL" row to "Earned SYMBOL". Since we no longer allow splits on AddressDriver accounts, calling this "splittable" was quite confusing.
- Hide "Splitting 0%" line if there's no splits applied to the current AddressDriver account (which should basically never be the case). The fact that we were still showing this is also quite confusing since you can no longer split directly from your AddressDriver account.
- Only show the cycle end DAY, not time, because we can't run the global splitting script exactly at that time every Thursday.
- Some copy adjustments.

Someone who is only collecting income from Drip Lists / Projects now sees the screen like this: 

<img width="718" alt="Screenshot 2023-09-26 at 14 26 15" src="https://github.com/drips-network/app/assets/1018218/32fcdee9-3e90-46ba-a85c-54b742b65f96">

2023-09-26 12:33 UTC, evvvritt commented
Looks good except I'd remove the "+" next to the earned amount in this simplified version. (Perhaps other contexts it still makes sense?)

2023-09-26 12:34 UTC, evvvritt requested changes
(remove the "+" next to the Earned amount in the simplified version)

2023-09-26 12:35 UTC, efstajas commented
> Looks good except I'd remove the "+" next to the earned amount in this simplified version. (Perhaps other contexts it still makes sense?)

good point, one sec!

2023-09-27 03:20 UTC, brandonhaslegs commented
- Should "Streams" be capitalized like Projects and Drip Lists?
- Instead of "on a weekly cycle" use "on a weekly basis"
- Can you actually only collect on a weekly cycle? Like if you miss the date, you have to wait another week to collect? Or is money **_added_** on a weekly cycle but you can **_collect_** at any time (after the first cycle)? Should make that more clear.
- Is there a situation where the two amounts would be different?
- In the first row, will the text "From Project or Drip Lists" change if funds have also come from Streams?

2023-10-02 15:17 UTC, brandonhaslegs approved these changes

2023-10-03 13:16 UTC, evvvritt approved these changes

2023-10-03 13:33 UTC, merged