wip
drips-network/app pull request #900
Opened 2024-01-12 11:12 UTC by efstajas

2024-01-15 14:09 UTC, efstajas commented
@evvvritt checks fail because the new GQL types for this aren't on prod yet, but they will be soon, then I'll re-run the checks. You can already take a look at the code :)

2024-01-23 09:23 UTC, efstajas commented
Do not merge until both infra slots are deployed with the new API changes. Currently only slot #1 has the changes deployed.

2024-01-23 12:54 UTC, evvvritt requested changes
Works well but think it should update or refresh the project profile page on tx confirm 🤓

2024-01-23 15:04 UTC, evvvritt approved these changes

2024-01-24 15:57 UTC, merged