restore drips logo on mobile when disconnected (closes #962)
drips-network/app pull request #990
Opened 2024-02-20 12:18 UTC by evvvritt

ALSO, moved Settings button to inside the Account Menu when wallet-connected (more space)

2024-02-20 12:37 UTC, brandonhaslegs commented
logo gets bigger in the app, should be identical to the landing page.

2024-02-20 14:33 UTC, evvvritt commented
(todo: remove "Code" from header as discussed in call)

2024-02-22 12:59 UTC, efstajas requested changes
looks like this for me:

<img width="447" alt="Screenshot 2024-02-22 at 13 59 12" src="https://github.com/drips-network/app/assets/1018218/ccc6406f-095b-467d-ac3b-cec18ba7eb36">

logo should shrink?

2024-02-22 13:00 UTC, efstajas commented
also let's remove the divider between profile and settings, would look cleaner imo

<img width="425" alt="Screenshot 2024-02-22 at 14 00 35" src="https://github.com/drips-network/app/assets/1018218/07e00ab7-8cf2-45ec-b7e1-dd30d0f4228e">

2024-02-22 14:30 UTC, brandonhaslegs commented
> logo should shrink?

Yes it should. Also it'll only shrink when you're connected to Goerli. Without that it should fit fine in there.

2024-02-23 05:10 UTC, jo-elimu commented on src/lib/components/header/header.svelte
> +    /* gap: 0.5rem; */
```suggestion
```

2024-02-23 05:11 UTC, jo-elimu approved these changes

2024-02-26 23:49 UTC, efstajas approved these changes
Is there no way to have the logo shrink dynamically based on available space…? It does that on the LP already. Maybe try removing `header/drips-logo.svelte` and just using `illustrations/logo.svelte`, perhaps together with a new max-width prop. It should be possible.

Either way, also OK to merge like this, but I find shrinking the logo to an arbitrary width based on which network you're connected to a bit awkward.

2024-02-27 12:30 UTC, jo-elimu approved these changes

2024-02-27 12:47 UTC, evvvritt commented
Ah sure didn't realize we had a second logo component. Yes, shrinking now automatically:
<img width="426" alt="Screenshot 2024-02-27 at 13 45 42" src="https://github.com/drips-network/app/assets/6071219/2858bb20-d533-4929-b0b3-df04a383e9c8">
<img width="436" alt="Screenshot 2024-02-27 at 13 46 19" src="https://github.com/drips-network/app/assets/6071219/cce885ed-ce48-46af-819c-42973a615977">

2024-02-27 13:09 UTC, jo-elimu approved these changes

2024-02-27 17:08 UTC, merged