add 4 extra featured projects to explore page
drips-network/app pull request #993
Opened 2024-02-21 23:58 UTC by SouravInsights

## Description:
Added `accountIds` of 4 extra projects ([nice-node](https://www.drips.network/app/projects/github/NiceNode/nice-node), [startkenet.js](https://www.drips.network/app/projects/github/starknet-io/starknet.js), [snapshot](https://www.drips.network/app/projects/github/snapshot-labs/snapshot) & [svelte-stepper](https://www.drips.network/app/projects/github/efstajas/svelte-stepper)) to the mainnet array of `FEATURED_PROJECT_ACCOUNT_IDS`.

## Screenshots:
![CleanShot 2024-02-22 at 04 48 32@2x](https://github.com/drips-network/app/assets/26466468/126f97a3-1e1d-4cd8-bf3e-61e892c86fbb)

## Note:
I'm not sure about the criteria to select featured projects, but as far as I understand, the consensus is to strike a balance between showcasing well-known projects and giving visibility to lesser-known projects that might deserve attention. Choosing popular projects potentially increase engagement within the platform while promoting newer or less recognized projects, foster diversity & encourage community growth. 

But currently, I have added **Nice Node**, **Snapshot** & **Starknet.js** and all 3 projects are well known so let me know if I need to include any other projects to the list. From a quick glance, I think [ens-normalize.js](https://github.com/adraffy/ens-normalize.js) is a cool one! Haven't explored all other projects as of now... Let me know your thoughts! @brandonhaslegs @efstajas

2024-02-22 07:52 UTC, brandonhaslegs commented
Hey thanks! Someone will take a look today. Can you mention which issue this closes so that it'll close the issue when the PR is merged?

2024-02-22 08:19 UTC, SouravInsights commented
> Hey thanks! Someone will take a look today. Can you mention which issue this closes so that it'll close the issue when the PR is merged?

Sure! This is the issue: https://github.com/drips-network/app/issues/971

2024-02-22 08:22 UTC, brandonhaslegs commented
Sorry btw I meant something like this:

closes #971

2024-02-22 08:31 UTC, SouravInsights commented
> Sorry btw I meant something like this:
> 
> closes #971

oh right right.. sorry!!

2024-02-22 10:11 UTC, efstajas commented on src/routes/app/(app)/+page.svelte
> +        '80927335273972468167722947750338907267861671542981060844246982983680', // startkenet.js
comment should be "starknet.js" :)

2024-02-22 14:31 UTC, evvvritt commented
thanks! can you please put `closes #971` in the title of this PR so when we squash and merge it will auto-close the issue?

2024-02-22 14:51 UTC, brandonhaslegs commented
> thanks! can you please put `closes #971` in the title of this PR so when we squash and merge it will auto-close the issue?

I think it still works as a comment right? We talked about that further up there 👆

2024-02-22 15:25 UTC, jo-elimu commented on src/routes/app/(app)/+page.svelte
> +        '80927335273972468167722947750338907267861671542981060844246982983680', // startkenet.js
```suggestion
        '80927335273972468167722947750338907267861671542981060844246982983680', // starknet.js
```

2024-02-22 16:56 UTC, evvvritt commented
No I think it needs to be in the title to auto-close (since title is used as the commit message which triggers the auto-close) @brandonhaslegs

2024-02-22 17:18 UTC, evvvritt commented
Code correct but is stacking 8 projects on mobile too tall? @brandonhaslegs

2024-02-22 19:23 UTC, SouravInsights commented
> Code correct but is stacking 8 projects on mobile too tall? @brandonhaslegs

I can think of 2 ideas..

- **Pagination:** We can split the 8 cards into smaller subsets, likes 4 cards per page and have controls to navigate between pages.

- **Carousel:** We can also have an horizontal carousel that allows users to swipe left or right to view cards. Although it's still a long list to scroll through but I think users are accustomed to swiping left or right to navigate through content on mobile devices, which makes horizontal scrolling feel natural and intuitive.

2024-02-22 21:12 UTC, brandonhaslegs commented
Good point. I think a horizontal overflow would be fine in mobile but need to design something. You can also suggest something directly in code if you'd like.

2024-02-22 21:14 UTC, efstajas commented
> No I think it needs to be in the title to auto-close (since title is used as the commit message which triggers the auto-close) @brandonhaslegs

it doesn't actually, just needs to be in the initial PR description. just added it there :) 

> No no, that's not what I meant! I mean we should definitely give visibility to lesser-known projects by individuals too. If all the featured projects are well known & popular then it would be not as diverse & maybe a bit misaligned. Bdw, I just checked out svelte-stepper & I think it's a cool project that deserve attention!

I got that, all good! I just think graph node should be featured for sure generally (because it's a big name), and am not super sure that featuring a project by one of the core maintainers of Drips is necessarily the best look, though I really appreciate that you like it 🙌 

> Code correct but is stacking 8 projects on mobile too tall?

... We could also just hide everything after the first 4 projects on mobile with a media query. Maybe a bit strange to have different content depending on screen size but I think in this instance it could be OK.

2024-02-22 21:14 UTC, efstajas commented
> No I think it needs to be in the title to auto-close (since title is used as the commit message which triggers the auto-close) @brandonhaslegs

it doesn't actually, just needs to be in the initial PR description. just added it there :) 

> No no, that's not what I meant! I mean we should definitely give visibility to lesser-known projects by individuals too. If all the featured projects are well known & popular then it would be not as diverse & maybe a bit misaligned. Bdw, I just checked out svelte-stepper & I think it's a cool project that deserve attention!

I got that, all good! I just think graph node should be featured for sure generally (because it's a big name), and am not super sure that featuring a project by one of the core maintainers of Drips is necessarily the best look, though I really appreciate that you like it 🙌 

> Code correct but is stacking 8 projects on mobile too tall?

... We could also just hide everything after the first 4 projects on mobile with a media query. Maybe a bit strange to have different content depending on screen size but I think in this instance it could be OK.

2024-02-23 00:39 UTC, SouravInsights commented
I've tried something simple to showcase all the 8 featured projects for smaller screen sizes. Do let me know your feedback! @brandonhaslegs @efstajas 

**Recording:** https://www.loom.com/share/f6be05a3fa7b40df964cdce7b3feb25f?sid=6f64f1bb-2afe-4e77-9c20-512620d4e9fd

2024-02-23 00:41 UTC, SouravInsights commented
Also, replaced `svelte-stepper` with `graph-node`

2024-02-23 05:24 UTC, jo-elimu approved these changes

2024-02-23 05:25 UTC, jo-elimu requested changes
There is a problem with "Build GQL types":

```
[STARTED] Load GraphQL schemas
[FAILED] 
[FAILED]         Failed to load schema from https://drips-api-mainnet-s1.up.railway.app/:
[FAILED] 
[FAILED]         Context creation failed: Unauthorized
[FAILED]         GraphQLError: Context creation failed: Unauthorized
```

2024-02-23 09:06 UTC, efstajas commented
@jo-elimu The reason this happens is because PRs from forked repos cannot access the target repo's secrets. In this case, it's failing, because one of those secrets is the GQL access token.

I'm not super sure how to fix this atm. Looking into it.

2024-02-23 09:44 UTC, efstajas commented
Alright, the test thing has bee fixed, tests should pass now 👌

2024-02-24 01:03 UTC, jo-elimu approved these changes

2024-02-27 23:38 UTC, SouravInsights commented
Have you guys tested this? Let me know if there's any issues with merging this @efstajas @evvvritt

2024-02-27 23:51 UTC, brandonhaslegs commented
Hey, so the overflow for this should be horizontal not vertical.

2024-02-28 11:52 UTC, SouravInsights commented
> Hey, so the overflow for this should be horizontal not vertical.

Yeah making it vertically scrollable was intentional.. But if you think horizontal is better then I'll make the necessary changes..

2024-02-28 11:59 UTC, brandonhaslegs commented
Yeah I think horizontal scroll is normal behavior, like on Instagram when you post multiple photos

2024-03-06 09:34 UTC, efstajas approved these changes
LGTM. 👍 

Ideally the scrolling would snap to project cards, but we can follow up with this.

2024-03-06 09:52 UTC, merged