chore: remove radicle design dependecy (closes #988)
drips-network/app pull request #997
Opened 2024-02-22 16:07 UTC by evvvritt

closes #988

2024-02-22 21:33 UTC, efstajas commented
Nice. I would try to get rid of the `design-system-emoji` component, and instead have the existing `Emoji.svelte` fall back to Twemoji directly.

2024-02-23 05:18 UTC, jo-elimu approved these changes

2024-02-23 14:02 UTC, efstajas requested changes
just one more thing :v:

2024-02-24 01:08 UTC, jo-elimu approved these changes

2024-02-26 13:47 UTC, evvvritt commented on src/lib/components/emoji/emoji.svelte
> +  }
`size` doesn't seem to have an effect because we're using svg's rather than their default png (?)

2024-02-26 15:58 UTC, evvvritt commented on src/lib/components/emoji/emoji.svelte
> +  }
fixed in [2ad82b6](https://github.com/drips-network/app/pull/997/commits/2ad82b65ab6521315d84960b504c3ba7a76bd2b4)*

2024-02-26 23:12 UTC, efstajas approved these changes
lgtm!

2024-02-27 11:43 UTC, jo-elimu approved these changes

2024-02-27 12:03 UTC, merged